name: nn
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  service_worker: ^0.2.3

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
